/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/earth2.glb --transform 
Files: public/earth2.glb [3.3MB] > C:\Users\Angith\Downloads\ecell\ecellwebsite\earth2-transformed.glb [473.6KB] (86%)
Author: IZ.MdVerz (https://sketchfab.com/IZ.MdVerz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-globe-hologram-2mb-looping-animation-37cac2803bbd4e9cad150a772215c343
Title: Earth globe hologram 2MB looping animation
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/earth2-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="Earth_2" rotation={[-Math.PI / 2, 0, 0.025]} scale={100}>
            <mesh name="Earth_2_Earth_Surface002_0" geometry={nodes.Earth_2_Earth_Surface002_0.geometry} material={materials['Earth_Surface.002']} />
          </group>
          <group name="Earth_rays_2" rotation={[-Math.PI / 2, 0, 0.025]} scale={100}>
            <mesh name="Earth_rays_2_transparent004_0" geometry={nodes.Earth_rays_2_transparent004_0.geometry} material={materials['transparent.004']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/earth2-transformed.glb')
